name: Main CI


on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - "deps.edn"
      - 'src/core/**/*.clj'
      - 'src/core/**/*.cljs'
      - 'src/core/**/*.cljc'
      - 'src/test/**/*.clj'
      - 'src/test/**/*.cljs'
      - 'src/test/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clojure-cli: "1.11.1.1347"
  java-version: '17'
  library: io.github.ajchemist/tools.user


jobs:
  test:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: [ "1.11" ]
    name: test @ CLJ = ${{ matrix.clojure }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: ${{ env.clojure-cli }}
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            cljdeps-${{ runner.os }}-


      - name: Install gopass
        run: |
          curl https://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg | sudo tee /usr/share/keyrings/gopass-archive-keyring.gpg >/dev/null
          cat << EOF | sudo tee /etc/apt/sources.list.d/gopass.sources
          Types: deb
          URIs: https://packages.gopass.pw/repos/gopass
          Suites: stable
          Architectures: all amd64 arm64 armhf
          Components: main
          Signed-By: /usr/share/keyrings/gopass-archive-keyring.gpg
          EOF
          sudo apt update
          sudo apt install gopass gopass-archive-keyring
          gpg --batch --gen-key <<EOF
          %no-protection
          Key-Type: 1
          Key-Length: 2048
          Subkey-Type: 1
          Subkey-Length: 2048
          Name-Real: Github Actions
          Name-Email: github-actions@example.com
          Expire-Date: 0
          EOF
          gopass init


      - name: Test runner
        env:
          TESTOPT: "-X:${{ matrix.clojure }}:provided:test:test-runner"
        run: |
          clojure $TESTOPT


      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
