name: Tools Test CI


on:
  push:
    paths:
      - '.github/workflows/tool.yml'
      - 'src/core/**/*.clj'
      - 'src/core/**/*.cljs'
      - 'src/core/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clojure-cli: "1.11.1.1347"
  java-version: '17'
  library: io.github.ajchemist/tools.user


jobs:
  test:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: [ "1.11" ]
    name: test @ CLJ = ${{ matrix.clojure }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: ${{ env.clojure-cli }}
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            cljdeps-${{ runner.os }}-


      - name: Install Tools
        run: |
          clojure -Ttools install io.github.ajchemist/tools.user '{:git/sha "${{ github.sha }}"}' :as tools.user


      - name: Prepare ssh-deploy job
        run: |
          clojure -Ttools.user ssh-keygen :ssh.key/id test/sample :pass/skip? true :ssh.keygen/nopassphrase true :ssh.keygen/type '"rsa"' :ssh.keygen/format '"PEM"' :ssh.keygen/comment '"This is a comment of key"'
          cat ~/.ssh/keypairs/test/sample.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          echo 'ssh_private_key<<EOF' >> $GITHUB_ENV
          cat ~/.ssh/keypairs/test/sample >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "whoami=$(whoami)" >> $GITHUB_ENV
          mkdir target
          cp ~/.ssh/keypairs/test/sample.pub target/
          cat /etc/ssh/sshd_config
          systemctl status ssh
          mkdir "${{ github.workspace }}/tmp"


      - name: Test ssh-deploy job
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ env.ssh_private_key }}
          ARGS: "-rltgoDzvO"
          SOURCE: "target/"
          REMOTE_HOST: "localhost"
          REMOTE_USER: ${{ env.whoami }}
          TARGET: "${{ github.workspace }}/tmp"


      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
